import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Support - RoastMyRoom",
};

const faqs = [
  {
    question: "How do I delete a scan?",
    answer:
      "Open the History tab, swipe left on the scan you want to remove, and tap Delete. You can also delete all scans from the Profile tab.",
  },
  {
    question: "How do I cancel my subscription?",
    answer:
      "Go to iOS Settings > Apple ID > Subscriptions > RoastMyRoom, then tap Cancel Subscription. Your access will continue until the end of the current billing period.",
  },
  {
    question: "How do I restore my purchases?",
    answer:
      "Open the App, go to Profile > Restore Purchases. This will restore any active subscriptions or lifetime purchases linked to your Apple ID.",
  },
  {
    question: "How do I delete my account and data?",
    answer:
      'You can sign out and delete your local data from Profile > Sign Out. To request deletion of any server-side data, email us at samuel.neveugall@gmail.com with the subject "Data Deletion Request".',
  },
  {
    question: "Why is my score different each time?",
    answer:
      "Scores are generated by AI and may vary slightly between scans of the same room due to differences in lighting, angle, and the probabilistic nature of AI models.",
  },
  {
    question: "What happens to my photos?",
    answer:
      "Photos are compressed and sent to our server for AI analysis only. They are not stored on our servers after processing. A local copy is kept on your device in your scan history.",
  },
];

export default function SupportPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 pt-28 pb-16">
      <h1 className="mb-2 text-3xl font-bold tracking-tight">Support</h1>
      <p className="mb-10 text-muted">
        Need help with RoastMyRoom? Check the FAQ below or reach out directly.
      </p>

      {/* Contact */}
      <div className="glass-card mb-12 rounded-2xl p-6">
        <h2 className="mb-3 text-lg font-semibold">Contact Us</h2>
        <p className="text-muted">
          Email us at{" "}
          <a
            href="mailto:samuel.neveugall@gmail.com"
            className="text-ai-purple transition-colors hover:text-ai-pink"
          >
            samuel.neveugall@gmail.com
          </a>
        </p>
        <p className="mt-2 text-sm text-muted">
          We typically respond within 48 hours.
        </p>
      </div>

      {/* FAQ */}
      <h2 className="mb-6 text-2xl font-bold tracking-tight">
        Frequently Asked Questions
      </h2>
      <div className="space-y-4">
        {faqs.map((faq) => (
          <div key={faq.question} className="glass-card rounded-2xl p-6">
            <h3 className="mb-2 font-semibold">{faq.question}</h3>
            <p className="text-sm leading-relaxed text-muted">{faq.answer}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
