import { Metadata } from "next";
import { LegalPage } from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Terms of Service - RoastMyRoom",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" lastUpdated="March 2, 2026">
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your use of the RoastMyRoom mobile
        application (&quot;the App&quot;), developed by Samuel Music (&quot;we&quot;, &quot;us&quot;,
        &quot;our&quot;). By using the App, you agree to these Terms.
      </p>

      <h2>1. Subscriptions</h2>
      <p>The App offers the following subscription plans:</p>
      <ul>
        <li>
          <strong>Weekly</strong> &ndash; Auto-renewable weekly subscription.
        </li>
        <li>
          <strong>Annual</strong> &ndash; Auto-renewable annual subscription.
        </li>
        <li>
          <strong>Lifetime</strong> &ndash; One-time, non-consumable purchase granting permanent
          access.
        </li>
      </ul>
      <p>
        Subscriptions are billed through <strong>Apple</strong> via your App Store account.
        Auto-renewable subscriptions will automatically renew unless cancelled at least 24 hours
        before the end of the current billing period. You can manage and cancel subscriptions in your
        iOS Settings &gt; Apple ID &gt; Subscriptions.
      </p>

      <h2>2. Points</h2>
      <p>
        The App offers consumable in-app purchase packs of points (10, 35, 75, or 200 points).
        Points are used to perform room scans beyond the free daily limit.
      </p>
      <ul>
        <li>Points are <strong>non-refundable</strong> once purchased.</li>
        <li>Points are <strong>non-transferable</strong> between accounts.</li>
        <li>
          Points may be synced across devices if you sign in with Apple ID.
        </li>
      </ul>

      <h2>3. Free Tier</h2>
      <p>
        All users receive <strong>2 free scans per day</strong>. Additional scans require points or
        an active subscription.
      </p>

      <h2>4. AI-Generated Content</h2>
      <p>
        Room scores, roasts, style assessments, and improvement tips are generated by artificial
        intelligence (OpenAI GPT-4o Vision). This content is provided{" "}
        <strong>for entertainment purposes only</strong> and does not constitute professional
        interior design, architectural, or any other professional advice.
      </p>
      <ul>
        <li>
          We make <strong>no guarantee of accuracy</strong> regarding AI-generated scores or
          feedback.
        </li>
        <li>AI results may vary for the same image.</li>
        <li>
          You should not rely on AI feedback for important decisions about your living space.
        </li>
      </ul>

      <h2>5. Intellectual Property</h2>
      <ul>
        <li>
          <strong>Your photos</strong> &ndash; You retain full ownership of any photos you take or
          select.
        </li>
        <li>
          <strong>AI-generated content</strong> &ndash; Scores, roasts, and tips generated by the
          App are licensed to you for <strong>personal, non-commercial use</strong>.
        </li>
        <li>
          <strong>App content</strong> &ndash; The App&apos;s design, code, branding, and assets are
          our intellectual property and may not be reproduced without permission.
        </li>
      </ul>

      <h2>6. Prohibited Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Abuse the App or attempt to bypass usage limits.</li>
        <li>Reverse engineer, decompile, or disassemble the App.</li>
        <li>Use the App or its output for unauthorized commercial purposes.</li>
        <li>Upload content that is illegal, harmful, or violates the rights of others.</li>
        <li>
          Attempt to manipulate points balances or exploit the scoring system.
        </li>
      </ul>

      <h2>7. Limitation of Liability</h2>
      <p>
        The App is provided &quot;as is&quot; without warranties of any kind. To the fullest extent
        permitted by law, we shall not be liable for any indirect, incidental, special, or
        consequential damages arising from your use of the App, including but not limited to loss of
        data, loss of profits, or reliance on AI-generated content.
      </p>

      <h2>8. Termination</h2>
      <p>
        We reserve the right to suspend or terminate your access to the App if you violate these
        Terms. You may stop using the App at any time.
      </p>

      <h2>9. Governing Law</h2>
      <p>
        These Terms are governed by and construed in accordance with the laws of{" "}
        <strong>France</strong>. Any disputes shall be subject to the exclusive jurisdiction of
        French courts.
      </p>

      <h2>10. Changes to These Terms</h2>
      <p>
        We may update these Terms from time to time. Continued use of the App after changes
        constitutes acceptance of the revised Terms.
      </p>

      <h2>11. Contact</h2>
      <p>
        For questions about these Terms, contact us at:{" "}
        <a href="mailto:samuel.neveugall@gmail.com">samuel.neveugall@gmail.com</a>
      </p>
    </LegalPage>
  );
}
